export let sampleResponse = [
  {
    title: 'Optimizing SSR Pages',
    authorName: 'Kiran',
    description: 'Lorem Ipsum here...',
    imageUrl: '',
    tags: ['Optimization', 'Design'],
    readTime: '5mins',
  },
  {
    title: 'Optimizing SSR Pages2',
    authorName: 'Kiran',
    description: 'Lorem Ipsum here...',
    imageUrl: '',
    tags: ['Optimization', 'Design'],
    readTime: '5mins',
  },
  {
    title: 'Optimizing SSR Pages3',
    authorName: 'Kiran',
    description: 'Lorem Ipsum here...',
    imageUrl: '',
    tags: ['Optimization', 'Design'],
    readTime: '5mins',
  },
  {
    title: 'Optimizing SSR Pages4',
    authorName: 'Kiran',
    description: 'Lorem Ipsum here...',
    imageUrl: '',
    tags: ['Optimization', 'Design'],
    readTime: '5mins',
  },
  {
    title: 'Optimizing SSR Pages5',
    authorName: 'Kiran',
    description: 'Lorem Ipsum here...',
    imageUrl: '',
    tags: ['Optimization', 'Design'],
    readTime: '5mins',
  },
  {
    title: 'Optimizing SSR Pages6',
    authorName: 'Kiran',
    description: 'Lorem Ipsum here...',
    imageUrl: '',
    tags: ['Optimization', 'Design'],
    readTime: '5mins',
  },
];
