// import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Classes from '../styles/Home.module.scss';
import Header from '../components/Header/Header';
import HeroBlog from '../components/HeroBlog/HeroBlog';
import PopularTags from '../components/PopularTags/PopularTags';
import PostGrid from '../components/PostGrid/PostGrid';
import Subscribe from '../components/Subscribe/Subscribe';
import Footer from '../components/Footer/Footer';

const Home = (props) => {
  return (
    <>
      <Head>
        <title>Project Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Classes.homeContainer}>
        {/****************** * 1 Header ****************** */}
        <header className={Classes.homeContainer__header}>
          <Header />
        </header>
        {/*******************  2 Hero Section (Blog of the day) ****************** */}
        <section className={Classes.homeContainer__heroBlog}>
          <HeroBlog />
        </section>
        <section className={Classes.homeContainer__popularTags}>
          <PopularTags />
        </section>
        <section className={Classes.homeContainer__postGrid}>
          <PostGrid posts={props.posts} />
        </section>
        <section className={Classes.homeContainer__subscribe}>
          <Subscribe />
        </section>
        <section className={Classes.homeContainer__footer}>
          <Footer />
        </section>
      </div>
    </>
  );
};

export async function getStaticProps() {
  const featuredPost = await fetch(
    'https://jsonplaceholder.typicode.com/posts'
  );
  const response = await featuredPost.json();
  console.log(response, 'response');
  return {
    props: {
      posts: response.slice(0, 6),
    },
  };
}

export default Home;
